name: PHPUnit

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: php-actions/composer@v6 # or alternative dependency management
    
    - name: PHPUnit Tests
      uses: php-actions/phpunit@v3
      env:
        TEST_NAME: phpunit
      with:
        bootstrap: vendor/autoload.php
        configuration: phpunit.xml
        args: --coverage-text
